### ISSUE TITLE
Building a slab with non-standard molecule

### ISSUE THREAD

**Issue by dpasserone** [nanotech-empa/aiidalab-empa-surfaces#88] opened 2022-04-07 09:25 UTC
Dear Developers,  @cpignedoli in particular

I have the following "molecule"(it is a flake of PbI2 monolayer)
```

48
Molecule PbI2 (48 atoms)
Pb         0.0000000000         0.0000000000         9.3674096700 
 Pb        -2.3300448635         4.0357577376         9.3674096700
 Pb        -4.6600897270         8.0715154753         9.3674096700
 Pb        -6.9901345905        12.1072732129         9.3674096700
 Pb         8.6933340000         2.3293710000         9.3674096700
 Pb         6.3632891365         6.3651287376         9.3674096700
 Pb         4.0332442730        10.4008864753         9.3674096700
 Pb         1.7031994095        14.4366442129         9.3674096700
 Pb        17.3866680000         4.6587420000         9.3674096700
 Pb        15.0566231365         8.6944997376         9.3674096700
 Pb        12.7265782730        12.7302574753         9.3674096700
 Pb        10.3965334095        16.7660152129         9.3674096700
 Pb        26.0800020000         6.9881130000         9.3674096700
 Pb        23.7499571365        11.0238707376         9.3674096700
 Pb        21.4199122730        15.0596284753         9.3674096700
 Pb        19.0898674095        19.0953862129         9.3674096700
 I         5.0188800000         2.8981700000        11.2348193400
 I         2.6888351365         6.9339277376        11.2348193400
 I         0.3587902730        10.9696854753        11.2348193400
 I        -1.9712545905        15.0054432129        11.2348193400
 I        13.7122140000         5.2275410000        11.2348193400
 I        11.3821691365         9.2632987376        11.2348193400
 I         9.0521242730        13.2990564753        11.2348193400
 I         6.7220794095        17.3348142129        11.2348193400
 I        22.4055480000         7.5569120000        11.2348193400
 I        20.0755031365        11.5926697376        11.2348193400
 I        17.7454582730        15.6284274753        11.2348193400
 I        15.4154134095        19.6641852129        11.2348193400
 I        31.0988820000         9.8862830000        11.2348193400
 I        28.7688371365        13.9220407376        11.2348193400
 I        26.4387922730        17.9577984753        11.2348193400
 I        24.1087474095        21.9935562129        11.2348193400
 I         1.3444100000         3.4669600000         7.5000000000
 I        -0.9856348635         7.5027177376         7.5000000000
 I        -3.3156797270        11.5384754753         7.5000000000
 I        -5.6457245905        15.5742332129         7.5000000000
 I        10.0377440000         5.7963310000         7.5000000000
 I         7.7076991365         9.8320887376         7.5000000000
 I         5.3776542730        13.8678464753         7.5000000000
 I         3.0476094095        17.9036042129         7.5000000000
 I        18.7310780000         8.1257020000         7.5000000000
 I        16.4010331365        12.1614597376         7.5000000000
 I        14.0709882730        16.1972174753         7.5000000000
 I        11.7409434095        20.2329752129         7.5000000000
 I        27.4244120000        10.4550730000         7.5000000000
 I        25.0943671365        14.4908307376         7.5000000000
 I        22.7643222730        18.5265884753         7.5000000000
 I        20.4342774095        22.5623462129         7.5000000000

```

I import the xyz files in the surfaces "build the slab" app
When I add the slab I get proposed a Au(111) size that is ok and the generated xyz I download includes a correct cell with enough vacuum.

![image](https://user-images.githubusercontent.com/45152275/162167155-2a322cdb-08b2-49b2-8f08-94d7252642af.png)

When visualizing the xyz with vmd, all is ok. But the lower I layer does not show up in aiida, although the corresponding Geo Opt importing the xyz slab runs nicely. 
It is not possible to select atoms etc. though in the visualizer. 

Regards,
Daniele

**Comment by yakutovicha** [comment] 2022-08-26 13:19
@dpasserone can you please double-check if the issue is still there? To me it worked fine, I see all the atoms:
![screenshot (7)](https://user-images.githubusercontent.com/13118485/186912718-2b1095f0-6a67-4eeb-a33d-2b48fdeebdb1.png)

**Comment by dpasserone** [comment] 2022-08-29 09:30
Seems good!

**Comment by yakutovicha** [comment] 2022-08-29 09:56
alright, then we close the issue. Thanks!

**Closed by yakutovicha** 2022-08-29 09:56 UTC
Labels: question
